# Generated by Django 3.2 on 2021-04-29 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateOfStart', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dateOfFinish', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('numOfLectures', models.IntegerField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
